### ISSUE TITLE
Contact info lost when cancelling registration

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#100]
I'm thinking we keep cancelled registrations in the db and show them on the registration-list page as a skinny bar that simply shows there was a reg and it was cancelled. Ideally that could be expanded and still offer call/text for cancelled participant. Otherwise you completely lose access to that person and their contact info when you cancel their reg.

**Comment by brimwd** [comment]
This is good. Researchers should only need participant info for getting them in the door, maybe for following up, and for compensating participants with e-gift cards after the session is complete.

I would actually like to update the server to delete all participant info 2 weeks after their session is complete to further reduce the risks associated with a security breach.
