### ISSUE TITLE
layout breaks on stupidly long words

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#101]
<img width="1280" alt="screen shot 2018-04-27 at 5 24 30 pm" src="https://user-images.githubusercontent.com/3270144/39389721-0a453a8e-4a40-11e8-987d-6bbd4a8c3a04.png">

**Comment by celloworld** [comment]
<img width="1037" alt="screen shot 2018-04-27 at 5 27 12 pm" src="https://user-images.githubusercontent.com/3270144/39389737-484d3354-4a40-11e8-803e-ad043079fdc4.png">
<img width="1014" alt="screen shot 2018-04-27 at 5 27 21 pm" src="https://user-images.githubusercontent.com/3270144/39389738-486fe6b0-4a40-11e8-83c9-047d1c855f48.png">

**Comment by brimwd** [comment]
Good catch.
I have a script for entering 'shy' hyphens in long words.
I might run that script when the page is rendered to create hyphenated word breaks in "long" words that will show up as needed.

**Comment by brimwd** [comment]
also applies to title, description, and address

**Comment by brimwd** [comment]
### Registration Page
<img width="773" alt="screen shot 2018-10-18 at 7 54 59 pm" src="https://user-images.githubusercontent.com/5776635/47196201-44178980-d314-11e8-8ef8-3da5cbd2f22f.png">
#### sign-up panel
<img width="634" alt="screen shot 2018-10-18 at 7 55 09 pm" src="https://user-images.githubusercontent.com/5776635/47196194-3d891200-d314-11e8-8b37-14d2fa1c63b4.png">

### List Page
<img width="858" alt="screen shot 2018-10-18 at 7 48 26 pm" src="https://user-images.githubusercontent.com/5776635/47196240-71643780-d314-11e8-8cc5-58539c3ea187.png">

### Create Study - review tab
<img width="871" alt="screen shot 2018-10-18 at 7 46 52 pm" src="https://user-images.githubusercontent.com/5776635/47196260-8a6ce880-d314-11e8-90dd-cb8001ab3161.png">

**Comment by brimwd** [comment]
Solving this & sanitizing data ended up being a breaking change.
All old studies will fail to render correctly.
