### ISSUE TITLE
list page: 'cancel day' button doesn't work

### ISSUE THREAD

**Issue by brimwd** [brimwd/usability#104]
once a day has been cancelled, it can't be reopened through the 'cancel day' button, nor through the individual toggles.

the button also does not switch the individual day toggles to 'off'

**Comment by brimwd** [comment]
The button needs to do 3 things:

1. if (all sessions are passed)
   * do nothing
1. else if (all sessions are closed)
   * reopen any sessions that have not passed
1. else // one or more sessions are open
   * needs to close all sessions
   * if any but it also needs to cancel all registrations.

**Comment by celloworld** [comment]
latest PR addresses #1 & #3 of the list you mentioned. there is a data persistence issue on the front end in the UI, will fix that and address #2 in next PR
