### ISSUE TITLE
After cancelling a session, session is removed from UI but not from registrations array

### ISSUE THREAD

**Issue by brimwd** [brimwd/usability#114]
If you navigate to a different day of sessions on the list view and then navigate to the day where you cancelled the session, the session is visible again.

Attempting to re-cancel the session crashes the server.

**Comment by celloworld** [comment]
what should happen when the day is cancelled?

**Comment by brimwd** [comment]
I just decremented the registered count on window.study.sessions[registeredSession] and added a .cancelled attribute to window.registrations[index] that I could check for when populating the registrations
