### ISSUE TITLE
Add TOS & Privacy Policy

### ISSUE THREAD

**Issue by brimwd** [brimwd/usability#12]

**Comment by celloworld** [comment]
_"How you, uh, how you comin' on that novel you're working on? Huh? Gotta— gotta compelling protagonist?"_ 
![afsd](https://user-images.githubusercontent.com/3270144/37374105-21e8d68e-26df-11e8-9311-c8bb8afac668.jpg)

**Comment by celloworld** [comment]
https://getterms.io/
https://termsfeed.com
https://www.freeprivacypolicy.com/

**Comment by brimwd** [comment]
https://github.com/brimwd/usability/commit/241101bb6907ab5bd5759a148d1a81c582916b28

Docs need review
