### ISSUE TITLE
closed session must also "pass" and remove toggle

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#144]
<img width="1267" alt="screen shot 2018-05-18 at 2 03 19 pm" src="https://user-images.githubusercontent.com/3270144/40257777-4e9858b4-5aa4-11e8-97b5-d464fa1231aa.png">

**Comment by brimwd** [comment]
What’s the issue? Repro steps?

**Comment by celloworld** [comment]
I think the underlying issue is that the page doesn't do any time-based updates once it's already rendered. We ought to scrape the futureSessions variable and set timeouts to close open sessions in the UI.
