### ISSUE TITLE
Group Size can be set to zero

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#189]
<img width="467" alt="screen shot 2018-06-07 at 11 45 20 am" src="https://user-images.githubusercontent.com/3270144/41119707-51b5e9e0-6a48-11e8-8ccd-be25eab0e428.png">

Toggling on Group Sessions populates the Maximum group size with the value 1
It seems like the intuitive default should be 2, and maybe even set a firm minimum of 2

**Comment by brimwd** [comment]
Group size is always referenced on the registration page. Group size is really just # of participants allowed to register per session

**Comment by brimwd** [comment]
It makes sense to make the default value in that field 2. 
The way we’re generating the study data, though, will require more logic to negotiate when that value is ‘1’ and when it can’t be 1.

**Comment by celloworld** [comment]
> Group size is really just # of participants allowed to register per session

Totally, and I've been thinking to restyle this option into a single prompt instead rather than an accordion of more actions to take

Number of Participants per session: [ 1  [⇅]]
(with min of 1)

**Comment by brimwd** [comment]
My only concern with changing this to ‘participants per session’ is that it
implies a guarantee that that many participants will be provided

**Comment by celloworld** [comment]
Max participants per session, then?

**Comment by brimwd** [comment]
I think “Max participants per session” makes sense if you are having group
sessions.
If your mindset/expectation is that sessions are 1:1, asking for the number
of participants per session might be confusing
