### ISSUE TITLE
Log in button

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#48]
when chrome browser autofills username and password, the log in button still appears grayed out until the form is touched

**Comment by brimwd** [comment]
maybe we should check if any of the fields are empty before graying out the button (run a function to fade/change the button to gray after load or some small delay)

**Comment by celloworld** [comment]
I like the idea and I tried something like this. Chrome doesn't seem to _actually_ populate the inputs until the screen is interacted with. The inputs still report that they are blank even reporting back after a 5 second timeout after rendering the page unless I clicked somewhere or pressed a key with the dom window focused.

**Comment by brimwd** [comment]
unfixable at this time -- Chrome doesn't populate username or password fields until the user touches them.

Removed the 'disabled' state from the login button in [this commit](https://github.com/brimwd/usability/pull/73/commits/1e46f149c8c3b64db7821deac0ca97240853d612) instead
