### ISSUE TITLE
Add more eligibility requirements with `enter`

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#50]
It'd be really smooth to be able to complete the eligibility req you're on and add another by pressing the `enter` key
<img width="724" alt="screen shot 2018-01-24 at 9 41 16 am" src="https://user-images.githubusercontent.com/3270144/35344692-fb68e572-00ea-11e8-97c3-cf98d23ba6ea.png">

**Comment by brimwd** [comment]
This might work:
```
/* requirementsInput  */.keyup(function(event){
    if(event.which === 13) {
        /* add new row */
    }
});
```

**Comment by brimwd** [comment]
good idea
