### ISSUE TITLE
Schedule error could be avoided

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#51]
<img width="742" alt="screen shot 2018-01-24 at 9 48 24 am" src="https://user-images.githubusercontent.com/3270144/35345789-c127ab2a-00ed-11e8-9dda-e03f432e8f79.png">

Weekdays/Weekends are both unchecked when you get to this section. Based on the ux of previous form fields, I assumed leaving these items untouched meant they'd both be selected since it's illogical to select neither. This then lead to an error on the review section.

<img width="735" alt="screen shot 2018-01-24 at 9 48 41 am" src="https://user-images.githubusercontent.com/3270144/35345798-c8872a8a-00ed-11e8-9222-e55f4287dea2.png">

As an aside, on the review page, the order of the green parallelogram headers doesn't coordinate to the create-study numbered sections. This complicates correcting a section with an error, and it'd be nice if a review section that's throwing an error had a direct link to the corresponding form section.

**Comment by brimwd** [comment]
moving to a [new issue](https://github.com/brimwd/usability/issues/74)

> on the review page, the order of the green parallelogram headers doesn't coordinate to the create-study numbered sections. This complicates correcting a section with an error, and it'd be nice if a review section that's throwing an error had a direct link to the corresponding form section.

**Comment by brimwd** [comment]
good idea to link to sections. completed in [this commit](https://github.com/brimwd/usability/commit/608c97e93a73c18717a6b7c9b8488c2da28857e7)
