### ISSUE TITLE
publish same study repeatedly -- too easy

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#57]
Upon creating a study, I received a success modal which was curiously at the very bottom of the screen and not padded from the bottom. I noticed that if I scrolled to the top of the screen, the links to each step of study creation were still there. I was able to click review and then create study again, duplicating it. After clicking create study, we need to either 
1) remove those controls at the top
2) put no-scroll on the body so you can only see the success modal and nested buttons
3) route them to the near-identical edit page and show the modal there

**Comment by brimwd** [comment]
Create/edit are the same page. 
Possible this issue can be solved as simply as updating page URL to /studyId/edit and re-running some of the basic page set-up functionality.
