### ISSUE TITLE
update study time removes end date

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#59]
begin with an ongoing study that has 'consecutive' selected in (3) Dates section in studies/:studyId/edit

Repro: 
be logged in
navigate to an existing ongoing study you admin
edit study
go to section (4) Times and change 'Day end' to a later time
go to section (6) Review and click 'Update Study'
go to section (3) Dates

Problem: the completion date constraint on section (3) Dates is removed. The registration page now reports that the study is closed.

Expected: no change in section (3) Dates

Other Thoughts: with the completion date constraint missing, the study decides there are no sessions instead of infinite. If that's what is intended, maybe leaving a constraint blank should throw an error?

**Comment by brimwd** [comment]
Can't reproduce at this time. Will check again later
