### ISSUE TITLE
`Check Changes` button doesn't display results of checkChanges()

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#65]
<img width="609" alt="screen shot 2018-04-03 at 6 41 29 pm" src="https://user-images.githubusercontent.com/3270144/38282713-e0b460b6-376e-11e8-9bc2-c5a06a96b6ee.png">

REPRO:
edit study > section 3 Dates > make a change? (idk when it shows up) > click `Check Changes` at bottom to the left of `Next Step` > nothing

**Comment by brimwd** [comment]
<img width="764" alt="screen shot 2018-04-08 at 3 26 36 pm" src="https://user-images.githubusercontent.com/5776635/38473226-42205348-3b41-11e8-98fd-7c29015805e2.png">

**Comment by celloworld** [comment]
Looking forward, these changes will:
create # sessions
maintain # copacetic sessions
and remove # incompatible sessions, **# of which already have registrants**

if incompatible sessions with registrants:

Proceed: [Keep only compatible registrations] or [Keep all registrations]
Cancel: [Never mind]

otherwise:
Proceed: [Get on with it!]
Cancel:  [No no no NO!]
