### ISSUE TITLE
cancel a session registration

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#67]
<img width="1247" alt="screen shot 2018-04-04 at 6 07 35 pm" src="https://user-images.githubusercontent.com/3270144/38343624-406bed2a-3842-11e8-8c53-a8dbbffb1414.png">

go to "View Registrations" click trash bin next to a registrant
if you click yes, the registration is cancelled and but there is no graphic response (click yes again and you get the db complaint at bottom)
click no, no response, prompt remains on screen

log:
jquery.min.js:4
DELETE http://localhost:3000/api/registrations/5a5d6b57a82bb91f8bdaa315/5ac567f6e7bb7ceb58c3c24d net::ERR_CONNECTION_REFUSED
send @ jquery.min.js:4
ajax @ jquery.min.js:4
(anonymous) @ list:282
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
list:290 {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …} "error" ""

**Comment by brimwd** [comment]
Just needs a 'slideUp()' method run on the row when it gets the success response from the server

**Comment by brimwd** [comment]
Didn't build that from the start because I wanted to do this:
1. fade out the buttons and text
1. change the background color of the row (maybe to navy?)
1. fade in the text "Registration cancelled"
1. pause for a few seconds
1. slide up the row

**Comment by brimwd** [comment]
Although we should probably prevent the 'cancel registration' function from firing twice
