### ISSUE TITLE
'Single' day studies should not allow you to set daily & total maximum sessions

### ISSUE THREAD

**Issue by brimwd** [brimwd/usability#93]
<img width="394" alt="screen shot 2018-04-13 at 9 00 09 am" src="https://user-images.githubusercontent.com/5776635/38745624-eb201328-3ef9-11e8-93b0-f5f39e1f8b62.png">
 
<img width="367" alt="screen shot 2018-04-13 at 9 00 04 am" src="https://user-images.githubusercontent.com/5776635/38745640-f6fa66da-3ef9-11e8-83ea-b8636e0e8669.png">

**Comment by celloworld** [comment]
This has been addressed by removing daily max if single is selected. I didn't do the fix it but it makes sense to leave total sessions
