### ISSUE TITLE
Safari doesn't acknowledge a lunch time being set even though it gets set 

### ISSUE THREAD

**Issue by brimwd** [brimwd/usability#95]
<img width="626" alt="screen shot 2018-04-13 at 8 59 57 am" src="https://user-images.githubusercontent.com/5776635/38745691-280bc822-3efa-11e8-8298-77b6aa5203c4.png">

**Comment by brimwd** [comment]
This is probably something in the 'collect data' function that fires when you hit the Review section.

**Comment by celloworld** [comment]
I am having this issue on Chrome v 66.0.3359.181 (Official Build) (64-bit) as well
